### ISSUE TITLE
MincLaplace ***Error in 'usr/bin/python': double free or corruption (!prev)

### ISSUE THREAD

**Issue by JA-Jones** [Mouse-Imaging-Centre/minclaplace#4]
Hi, I am running MINC on a ubuntu (16.04) VM. Minc is installed (checked via mincinfo - returns Usage etc). Pyminc is also installed (locate pyminc gives location in '/lib/python2.7/dist-packages/pyminc'). Minclaplace is also installed correctly as command 'minclaplace' gives subsequent instruction for input. However, when I try to run 'minclaplace' with my template I get ' ***Error in 'usr/bin/python': double free or corruption (!prev)'. I think this may be a memory allocation problem, but I am unsure. I have also downloaded the VM from the cobralab github with MINC/PYMINC already installed. I have installed minclaplace on this also and get an error of 'malloc_consolidate(): invalid chunk size, aborted (core dumped)' when running the command with my template. Could you please advise on the amount of memory and storage required for these processes. If possible, is there any test images online, e.g. the template from the minclaplace/laplacegrid and representative csv file that I could download and use to compare with my images? (The attached file is the output from the ubuntu vm (not the pre-made MINC lubuntu setup from cobralab)). My template is consistent with the one outlined in the LaplaceGrid page (with central portion of the brain (non-cortex) being 0, the middle (or cortical column) having a voxel value of 5, the resistive portion = 20 and outside the brain being set to 10. 

Thanks in advance! Kind regards,
Jolyon

[minc_laplace_output (2).txt](https://github.com/Mouse-Imaging-Centre/minclaplace/files/4075779/minc_laplace_output.2.txt)

**Comment by JA-Jones** [comment]
Issue closed as bug no longer present. Software successfully installed.

**Comment by gdevenyi** [comment]
We would appreciate if you could document what the problem was. Thanks.
